trydjango1-11/src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView



from contacts.views import (
	contact_create_view,
	contacts_list_view,
	ContactsListView,
	ContactsDetailView,
	UserContactsCreateView
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^', include('contacts.urls', namespace='contacts')),
    url(r'^quotes/', include('quotes.urls', namespace='quotes')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

trydjango1-11/src/quotes/urls.py
from django.conf.urls import url
from django.contrib import admin




from .views import (
	QuoteCreateView,
	QuoteDetailView,
	QuoteListView
)

urlpatterns = [
    url(r'^$', QuoteListView.as_view(), name='list'),
    url(r'^create/$', QuoteCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', QuoteDetailView.as_view(), name='detail'),
]

trydjango1-11/src/quotes/models.py
from django.conf import settings
from django.db import models

from contacts.models import UserContacts
from django import forms



class Quote(models.Model):
	# choices
	motivational 		= 'MOT'
	spiritual	 		= 'SPR'
	funny				= 'LOL'
	TYPE_OF_QUOTE			= (
			(motivational, 'motivational'),
			(spiritual, 'spiritual'),
			(funny, 'funny'),
	)
	# associations
	user 				= models.ForeignKey(settings.AUTH_USER_MODEL)
	contact 			= models.ForeignKey(UserContacts)
	# quote type 
	quote_type			= models.CharField(max_length=3, choices=TYPE_OF_QUOTE,)
	postscript 			= models.TextField(blank=True, null=True)
	public 				= models.BooleanField(default=True)
	
	timestamp 			= models.DateTimeField(auto_now_add=True)
	updated 			= models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['-updated', '-timestamp'] # gives the lastest when you do Quote.objects.all()

trydjango1-11/src/quotes/forms.py
from django import forms


from .models import Quote

class QuoteForm(forms.ModelForm):
	class Meta:
		model = Quote
		fields = [
			'contact',
			'quote_type',
			'postscript',
			'public'
		]

trydjango1-11/src/quotes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import QuoteForm
from .models import Quote


class QuoteListView(ListView):
	def get_queryset(self):
		return Quote.objects.filter(user=self.request.user)


class QuoteDetailView (DetailView):
	def get_queryset(self):
		return Quote.objects.filter(user=self.request.user)


class QuoteCreateView(CreateView):
	def get_queryset(self):
		return Quote.objects.filter(user=self.request.user)

class QuoteUpdateView(UpdateView):
	def get_queryset(self):
		return Quote.objects.filter(user=self.request.user)

trydjango1-11/src/quotes/templates/quotes/quote_list.html
{% extends "base.html" %}

{% block head_title %} Add Quote || {{ block.super }}{% endblock head_title %}

{% block content %}
<div class="float-right">
  <a class="btn btn-primary btn-sm" href="{% url 'contacts:create' %}">Add Contact</a>
</div>
</h1> 

<table class="table table-striped" >
	
  <thead>
    <tr>
      <th> </th>
      <th>Name</th>
      <th>Phone</th>
      <th>Location</th>
      {% for obj in object_list %}
    </tr>
      
  </thead>
  <tbody>
    <tr class="table table-striped">
      <th scope="row"></th>
      <td><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</td>
      <td>{{ obj.phone }}</td>
      <td>{{ obj.location }}</td>
    </tr>
  </tbody>
  	{% endfor %}
</table>
{% endblock content %}