trydjango1-11/src/delivery/urls.py
from django.conf.urls import url
from django.contrib import admin


from delivery.views import (
    AppointmentListView,
    AppointmentCreateView,
    AppointmentDetailView,
    AppointmentUpdateView,
    AppointmentDeleteView

) 


urlpatterns = [
    # List and detail views
    url(r'^$', AppointmentListView.as_view(), name='list_appointments'),
    url(r'^(?P<pk>[0-9]+)$', AppointmentDetailView.as_view(), name='view_appointment'),

    # Create, update, delete
    url(r'^new$', AppointmentCreateView.as_view(), name='new_appointment'),
    url(r'^(?P<pk>[0-9]+)/edit$', AppointmentUpdateView.as_view(), name='edit_appointment'),
    url(r'^(?P<pk>[0-9]+)/delete$', AppointmentDeleteView.as_view(), name='delete_appointment'),
]

trydjango1-11/src/quotes/urls.py
from django.conf.urls import url
from django.contrib import admin




from .views import (
	QuoteCreateView,
	QuoteDetailView,
	QuoteListView
)

urlpatterns = [
    url(r'^$', QuoteListView.as_view(), name='list'),
    url(r'^create/$', QuoteCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', QuoteDetailView.as_view(), name='detail'),
]

trydjango1-11/src/delivery/models.py
from __future__ import unicode_literals

from appointments.settings import common
from contacts.models import UserContacts
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from timezone_field import TimeZoneField


import arrow


@python_2_unicode_compatible
class Appointment(models.Model):
	user 			= models.ForeignKey(settings.AUTH_USER_MODEL)
	user_contact	= models.ForeignKey(UserContacts)
	name 			= models.CharField(max_length=150)
	phone_number 	= models.CharField(max_length=15)
	time 			= models.DateTimeField()
	time_zone 		= TimeZoneField(default='US/Eastern')

    # Additional fields not visible to users
	task_id = models.CharField(max_length=50, blank=True, editable=False)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
	    return 'Appointment #{0} - {1}'.format(self.pk, self.name)

	def get_absolute_url(self):
	    return reverse('view_appointment', args=[str(self.id)])

	def clean(self):
	    """Checks that appointments are not scheduled in the past"""

	    appointment_time = arrow.get(self.time, self.time_zone.zone)

	    if appointment_time < arrow.utcnow():
	        raise ValidationError('You cannot schedule an appointment for the past. Please check your time and time_zone')

	def schedule_reminder(self):
	    """Schedules a Celery task to send a reminder about this appointment"""

	    # Calculate the correct time to send this reminder
	    appointment_time = arrow.get(self.time, self.time_zone.zone)
	    reminder_time = appointment_time.replace(minutes=-settings.REMINDER_TIME)

	    # Schedule the Celery task
	    from .tasks import send_sms_reminder
	    result = send_sms_reminder.apply_async((self.pk,), eta=reminder_time)

	    return result.id

	def save(self, *args, **kwargs):
	    """Custom save method which also schedules a reminder"""

	    # Check if we have scheduled a reminder for this appointment before
	    if self.task_id:
	        # Revoke that task in case its time has changed
	        celery_app.control.revoke(self.task_id)

	    # Save our appointment, which populates self.pk,
	    # which is used in schedule_reminder
	    super(Appointment, self).save(*args, **kwargs)

	    # Schedule a new reminder task for this appointment
	    self.task_id = self.schedule_reminder()

	    # Save our appointment again, with the new task_id
	    super(Appointment, self).save(*args, **kwargs)

trydjango1-11/src/delivery/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render 
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .models import Appointment

class AppointmentListView(ListView):
    """Shows users a list of appointments"""

    model = Appointment


class AppointmentDetailView(DetailView):
    """Shows users a single appointment"""

    model = Appointment


class AppointmentCreateView(SuccessMessageMixin, CreateView):
    """Powers a form to create a new appointment"""

    model = Appointment
    fields = ['name', 'phone_number', 'time', 'time_zone']
    success_message = 'Appointment successfully created.'


class AppointmentUpdateView(SuccessMessageMixin, UpdateView):
    """Powers a form to edit existing appointments"""

    model = Appointment
    fields = ['name', 'phone_number', 'time', 'time_zone']
    success_message = 'Appointment successfully updated.'


class AppointmentDeleteView(DeleteView):
    """Prompts users to confirm deletion of an appointment"""

    model = Appointment
    success_url = reverse_lazy('list_appointments')

# Create your views here.

trydjango1-11/src/templates/delivery/appointment_form.html
{% extends "base.html" %}

{% block title %}New reminder{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">
      <div class="page-header">
        <h1>
          {% if not object.pk %}
            New appointment
          {% else %}
            Edit appointment
          {% endif %}
          </h1>
      </div>

      <form class="form-horizontal" method="post">
        {% csrf_token %}
       
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <a href="#back" class="btn btn-default">Cancel</a>
            <button type="submit" class="btn btn-primary">
              {% if not object.pk %}
                Create appointment
              {% else %}
                Update appointment
              {% endif %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block page_css %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block page_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

  <script type="text/javascript">
      $(function() {
          $('#id_time').datetimepicker({
            format: 'MM/DD/YYYY HH:mm',
            extraFormats: ['YYYY-MM-DD HH:mm:ss'],
            sideBySide: true
          });
      });
  </script>
{% endblock %}

trydjango1-11/src/templates/delivery/appointment_list.html
{% extends "base.html" %}

{% block title %}Upcoming reminders{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">

      <div class="page-header">
        <h1>Appointments</h1>
      </div>

      {% if not object_list %}
        <p><strong>No upcoming appointments.</strong> Why not <a href="{% url 'new_appointment' %}">schedule one?</a>
      {% endif %}

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Phone number</th>
            <th>Time</th>
            <th>Created at</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for appointment in object_list %}
            <tr>
              <td><a href="{{ appointment.get_absolute_url }}">{{ appointment.pk }}</a></td>
              <td>{{ appointment.name }}</td>
              <td>{{ appointment.phone_number }}</td>
              <td>{{ appointment.time }}</td>
              <td>{{ appointment.created }}</td>
              <td>
                <a class="btn btn-default btn-xs" href="{% url 'edit_appointment' appointment.pk %}">Edit</a>
                <a class="btn btn-xs btn-danger" href="{% url 'delete_appointment' appointment.pk %}">Delete</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <a class="btn btn-primary" href="{% url 'new_appointment' %}">New</a>
    </div>
  </div>
{% endblock %}