trydjango1-11/src/contacts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView




from .views import (
	# contact_create_view,
	# contacts_list_view,
	ContactsListView,
	ContactsDetailView,
	UserContactsCreateView
)

urlpatterns = [
    url(r'^list$', ContactsListView.as_view(), name='list'),
    url(r'^$', UserContactsCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', ContactsDetailView.as_view(), name='detail'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

trydjango1-11/src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView



from contacts.views import (
	contact_create_view,
	contacts_list_view,
	ContactsListView,
	ContactsDetailView,
	UserContactsCreateView
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^', include('contacts.urls', namespace='contacts')),
    url(r'^quotes/', include('quotes.urls', namespace='quotes')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

trydjango1-11/src/quotes/urls.py
from django.conf.urls import url
from django.contrib import admin




from .views import (
	QuoteCreateView,
	QuoteDetailView,
	QuoteListView
)

urlpatterns = [
    url(r'^$', QuoteListView.as_view(), name='list'),
    url(r'^create/$', QuoteCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', QuoteDetailView.as_view(), name='detail'),
]

trydjango1-11/src/contacts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

import schedule
import datetime
import time 
import random

from .utils import (unique_slug_generator, account_sid, auth_token, client, my_twilio, welcome_message,test_message, send_welcome_message, contacts_to_message,
my_quote)
from .validators import validate_timezone, is_valid_number


class UserContacts(models.Model):
	
	name	 	= models.CharField(max_length=120)
	phone 	 	= models.IntegerField(validators=[is_valid_number])
	location 	= models.CharField(max_length=120, null=True, blank=True)
	timestamp 	= models.DateTimeField(auto_now_add=True)
	slug 		= models.SlugField(null=True, blank=True)
	time_zone 	= models.CharField(max_length=120, validators=[validate_timezone])

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		# return f'/contact-detail/{self.slug}'
		return reverse('contacts:detail', kwargs={'slug': self.slug})


	
	@property 
	def title(self):
		return self.name # allows us to say obj.title

	class Meta:
		verbose_name = 'User Contact'
		verbose_name_plural ='User Contacts'
	
def uc_pre_save_reciever(sender, instance, *args, **kwargs):
	instance.time_zone = instance.time_zone.capitalize()
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)


def uc_post_save_reciever(sender, instance, created, *args, **kwargs):
	name = instance.name
	cell = instance.phone
	new_contact = {name:cell}
	welcome_data = {
		'to': cell, 
		'from_': my_twilio, 
		'body': my_quote()
	}
	send_welcome_message(**welcome_data)
	contacts_to_message.update(new_contact)
	print(contacts_to_message)
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)
		instance.save()

# def send_quote_to_multi_contacts():
# 	q = UserContacts.objects.values('phone')
# 	for phone in q:
# 		message.client.messages.create(to=phone, from_=my_twilio, body=test_message)


# while True:
#     schedule.run_pending()
#     time.sleep(1)


# schedule.every().day.at("16:38").do(send_qoute_to_multi_contacts)


	
pre_save.connect(uc_pre_save_reciever, sender=UserContacts)

post_save.connect(uc_post_save_reciever, sender=UserContacts)

	

trydjango1-11/src/contacts/forms.py
from django import forms
from .models import UserContacts 
from .validators import validate_timezone



class UserContactsCreateForm(forms.ModelForm):
	# name = forms.CharField(widget=forms.TextInput(
	#     attrs={
	#         'class': 'form-group',
	#         'placeholder': 'Name'
	#     }
	# ))

	phone = forms.CharField(widget=forms.TextInput(
	    attrs={
	        'class': 'form-group',
	        'placeholder': 'Phone'
	    }
	))
		
	class Meta:
		model = UserContacts
		fields =[
			'phone'
		]

	# def clean_phone(self):
	# 	phone = self.cleaned_data.get("phone")
	# 	qs = UserContacts.objects.filter(phone__iexact=phone)
	# 	if qs.exists():
	# 		raise forms.ValidationError('Phone Number already registered')
	# 	return phone

trydjango1-11/src/contacts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView

from .forms import  UserContactsCreateForm #ContactCreateForm,
from .models import UserContacts

User = settings.AUTH_USER_MODEL


@login_required()
def contact_create_view(request):
	form = UserContactsCreateForm(request.POST or None)
	errors = None
	if form.is_valid():
		if request.user.is_authenticated():
			instance = form.save(commit=False)
			instance.owner = request.user
			instance.save() 
			return HttpResponseRedirect('/contacts_list/')
		else:
			return HttpResponseRedirect('/login/')
	if form.errors: 
		errors = form.errors
			
	template_name = 'contacts/contacts_list_form.html'
	context = {"form": form, "errors": errors}
	return render(request, template_name, context) 


def contacts_list_view(request):
	template_name = 'contacts/contacts_list.html'
	queryset = UserContacts.objects.all()
	context = {
		"object_list": queryset
	}
	return render(request, template_name, context)


class ContactsListView(ListView):	
	def get_queryset(self):
		slug = self.kwargs.get('slug')
		if slug:
			queryset = UserContacts.objects.filter(
					Q(location__iexact=slug) |
					Q(location__icontains=slug) # you should remove this if you wanna do state abbrevations
				)
		else:
			queryset = UserContacts.objects.all()
		return queryset


class ContactsDetailView(DetailView):
	queryset = UserContacts.objects.all() #filter(location__iexact='nys') #filer it by user

class UserContactsCreateView(CreateView):
	form_class = UserContactsCreateForm
	template_name = 'contacts/contacts_list_form.html'
	# success_url = '/contacts-list/'

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.owner = None
		return super(UserContactsCreateView, self).form_valid(form)

trydjango1-11/src/templates/about.html
{% extends "base.html" %}

{% block head_title %} ABout || {{ block.super }} {% endblock head_title %}


{% block content %}
<h1> About </h1>
{% include 'snippets/sidebar.html' %}
{% endblock content %}



<!-- django templates can have variables, conditionals, loops  -->

trydjango1-11/src/templates/base.html
<!DOCTYPE html>
<html lang=en>

<head>
<title>{% block head_title %}e11:e.io{% endblock head_title %}</title>
{% include 'snippets/css.html' %}
</head>
<body>
{% include 'snippets/nav.html' %}

<div class="container">
{% block content%}{% endblock content%}
</div>

{% include 'snippets/js.html' %}

</body>
</hmtl>


<!-- django templates can have variables, conditionals, loops  -->

trydjango1-11/src/templates/contact.html
{% extends "base.html" %}

{% block head_title %} Contact || {{ block.super }} {% endblock head_title %}


{% block content %}
<h1> Contact </h1>
{% include 'snippets/sidebar.html' %}
<a href="mailto:georgesp90@gmail.com">Email us</a>
{% endblock content %}


<!-- django templates can have variables, conditionals, loops  -->

trydjango1-11/src/templates/home.html
{% extends "landing_base.html" %}
{% block head_title %}{{ block.super }}{% endblock head_title %}
{% block content %}
<div class="jumbotron jumbotron-fluid" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

  <div class="container">
    <div >
    <h1 class="display-1" class="mx-auto" style="width: 200px;">header here</h1>
    <p class="lead">Inspiration a text away</p>
    <p class="lead">
    </div>
    {% if user.is_authenticated %}
    <a class="btn btn-primary btn-lg" href="{% url 'contacts:list' %}" role="button">Contacts</a>
    {% else %}
    
    <a class="btn btn-primary btn-lg" href="/about/" role="button">About</a>
    <a class="btn btn-primary btn-lg" href="/login/" role="button">Login</a>

    {% endif %}
    
  </p>
  </div>
</div>

{% endblock content %}

trydjango1-11/src/templates/landing_base.html
<!DOCTYPE html>
<html lang=en>

<head>
<title>{% block head_title %}e11:e.io{% endblock head_title %}</title>
{% include 'snippets/css.html' %}
</head>
	<body >


	<div>
	{% block content%}{% endblock content%}
	</div>

	{% include 'snippets/js.html' %}

	</body>
</hmtl>
<!-- "{% include 'snippets/nav.html' %}